# ${projectName}

This project was generated by WagDuck.

## Building the Project

Use the following command to build the project:

<#if buildTool == "gradle">
```bash
./gradlew build
```
<#else> <#-- Assume Maven -->
```bash
mvn clean install
```
</#if>

## Running the Project

You can run the application using:

<#if buildTool == "gradle">
```bash
./gradlew bootRun
```
<#else> <#-- Assume Maven -->
```bash
mvn spring-boot:run
```
</#if>

The application will be available at `http://localhost:8080` (or the configured port).

## API Documentation

If OpenAPI/Swagger is enabled, API documentation is available at:

*   Swagger UI: `http://localhost:8080/swagger-ui.html`
*   API Docs (JSON): `http://localhost:8080/api-docs`