# ${projectName}

This project was generated by WagDuck.

## Requirements

- [Go 1.21+](https://golang.org/dl/)
- [Gin](https://github.com/gin-gonic/gin)
- (Optional) [GORM](https://gorm.io/) for database access

## Getting Started

```bash
go mod tidy
go run ./cmd/${projectModuleName}/main.go
```

## Project Structure

- `cmd/${projectModuleName}/` - Entrypoint (`main.go`)
- `internal/api/` - HTTP handlers (controllers)
- `internal/service/` - Business logic
- `internal/repository/` - Data access
- `internal/model/` - Domain models & DTOs
- `internal/mapper/` - Mapping logic (if needed)
- `internal/config/` - App configuration

## API Documentation

API documentation with Swagger can be generated using [swaggo/swag](https://github.com/swaggo/swag).

## Docker

Build and run:

```bash
docker build -t ${projectModuleName}:latest .
docker run -p 8080:8080 ${projectModuleName}:latest
```